### ISSUE TITLE
npm adduser no response

### ISSUE THREAD

**Issue by mailbyms** [Kubernetes-Best-Pratice/verdaccio#1]
web page is normal, my is http://192.168.1.176:4873
as guided, I type  
npm adduser --registry http://192.168.1.176:4873

and errors pop up:
10 verbose adduser before first PUT { _id: 'org.couchdb.user:jane',
10 verbose adduser   name: 'jane',
10 verbose adduser   password: 'XXXXX',
10 verbose adduser   email: 'mike@email.hk',
10 verbose adduser   type: 'user',
10 verbose adduser   roles: [],
10 verbose adduser   date: '2020-06-16T10:18:00.007Z' }
11 http fetch PUT 500 http://192.168.1.176:4873/-/user/org.couchdb.user:jane 70085ms attempt #3
12 verbose stack Error: 500 Internal Server Error - PUT http://192.168.1.176:4873/-/user/org.couchdb.user:jane - internal server error
12 verbose stack     at res.buffer.catch.then.body (/usr/local/node-v10.21.0-linux-x64/lib/node_modules/npm/node_modules/npm-registry-fetch/check
-response.js:104:15)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose statusCode 500
14 verbose cwd /root/build/storage-service-master/node_modules/dmai-base-log/package

**Comment by colynn** [comment]
Maybe it's a client problem, FYI [npm adduser](https://docs.npmjs.com/cli/adduser)

And you also can check logs use `docker-compose logs -f verdaccio`
